version: "3"

services:
  server:
    image: srcrs/rss-readerpro:latest
    container_name: rss-reader
    restart: always
    ports:
      - "5237:5237"
    volumes:
      - "$PWD/config.json:/app/config.json"
